name: pr-validation
on:
  pull_request:
    branches:
      - develop

jobs:
  develop-pr-linting-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      
      - name: Lint HTML and CSS
        run: |
          npx htmlhint "**/*.html"
          npx stylelint "**/*.css"
          
  develop-pr-build-job:
    runs-on: ubuntu-latest
    needs: develop-pr-linting-job
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      
      - name: Build Website
        run: npx parcel build "./src/index.html" --dist-dir "./dev" --public-url "./"
